import type { Metadata } from "next";
import localFont from "next/font/local";
import Footer from "./components/Layout/Footer";
import Header from "./components/Layout/Header";
import Menu from "./components/Layout/Menu";
import "./assets/scss/themes.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const materialdesignicons = localFont({
  src: [
    {
      path: "./assets/fonts/materialdesignicons-webfont.eot",
    },
    {
      path: "./assets/fonts/materialdesignicons-webfont.woff",
    },
    {
      path: "./assets/fonts/materialdesignicons-webfont.woff2",
    },
    {
      path: "./assets/fonts/materialdesignicons-webfont.ttf",
    },
  ],
  variable: "--font-materialdesignicons",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      data-layout="horizontal"
      data-topbar="light"
      data-sidebar-size="lg"
      data-sidebar="light"
      data-sidebar-image="none"
      data-preloader="disable"
      data-sidebar-visibility="show"
      data-layout-style="default"
      data-bs-theme="dark"
      data-layout-width="fluid"
      data-layout-position="fixed"
    >
      <head>
        <meta charSet="utf-8" />
        <title>CS2-stats</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={`${materialdesignicons.variable} font-sans`}>
        <div id="layout-wrapper">
          <Header />
          <Menu />
          <div className="main-content">
            <div className="page-content">
              <div className="container-fluid">{children}</div>
            </div>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
